# Generated by Django 5.2.3 on 2025-11-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentLocation',
        ),
    ]
