# Generated by Django 5.2.3 on 2025-11-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_delete_currentlocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
