# Generated by Django 5.2.3 on 2025-11-11 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='area',
            new_name='language',
        ),
    ]
