from .views.apis.sales_apis import (list_unverified_sales_api,
approve_sale_api,
reject_sale_api,
list_approved_sales_api,
list_rejected_sales_api,
list_all_sales_api,
get_sale_details_api,
get_sales_summary_api,
get_product_sales_api,
get_daily_sales_api,
get_monthly_sales_api,
get_yearly_sales_api,
get_sales_by_date_range_api,
get_top_selling_products_api,
get_sales_statistics_api,
get_pending_sales_count_api,
get_approved_sales_count_api,
get_rejected_sales_count_api,
get_total_revenue_api,
get_total_products_sold_api,
get_average_sale_value_api,
get_highest_sale_api,
get_lowest_sale_api,
get_sales_trends_api,
get_product_sales_summary_api,
get_recent_sales_api,
get_sales_count_api,
get_total_sales_amount_api,
get_average_units_sold_per_sale_api,
get_sales_growth_rate_api,
get_average_order_value_api)
from django.urls import path
url_patterns = [
    path('sales/list_unverified_sales_api/', list_unverified_sales_api, name='list_unverified_sales_api'),
    path('sales/approve_sale_api/<int:pk>/', approve_sale_api, name='approve_sale_api'),
    path('sales/reject_sale_api/<int:pk>/', reject_sale_api, name='reject_sale_api'),
    path('sales/list_approved_sales_api/', list_approved_sales_api, name='list_approved_sales_api'),
    path('sales/list_rejected_sales_api/', list_rejected_sales_api, name='list_rejected_sales_api'),
    path('sales/list_all_sales_api/', list_all_sales_api, name='list_all_sales_api'),
    path('sales/get_sale_details_api/<int:pk>/', get_sale_details_api, name='get_sale_details_api'),
    path('sales/get_sales_summary_api/', get_sales_summary_api, name='get_sales_summary_api'),
    path('sales/get_product_sales_api/<int:product_id>/', get_product_sales_api, name='get_product_sales_api'),
    path('sales/get_daily_sales_api/', get_daily_sales_api, name='get_daily_sales_api'),
    path('sales/get_monthly_sales_api/', get_monthly_sales_api, name='get_monthly_sales_api'),
    path('sales/get_yearly_sales_api/', get_yearly_sales_api, name='get_yearly_sales_api'),
    path('sales/get_sales_by_date_range_api/', get_sales_by_date_range_api, name='get_sales_by_date_range_api'),
    path('sales/get_top_selling_products_api/', get_top_selling_products_api, name='get_top_selling_products_api'),
    path('sales/get_sales_statistics_api/', get_sales_statistics_api, name='get_sales_statistics_api'),
    path('sales/get_pending_sales_count_api/', get_pending_sales_count_api, name='get_pending_sales_count_api'),
    path('sales/get_approved_sales_count_api/', get_approved_sales_count_api, name='get_approved_sales_count_api'),
    path('sales/get_rejected_sales_count_api/', get_rejected_sales_count_api, name='get_rejected_sales_count_api'),
    path('sales/get_total_revenue_api/', get_total_revenue_api, name='get_total_revenue_api'),
    path('sales/get_total_products_sold_api/', get_total_products_sold_api, name='get_total_products_sold_api'),
    path('sales/get_average_sale_value_api/', get_average_sale_value_api, name='get_average_sale_value_api'),
    path('sales/get_highest_sale_api/', get_highest_sale_api, name='get_highest_sale_api'),
    path('sales/get_lowest_sale_api/', get_lowest_sale_api, name='get_lowest_sale_api'),
    path('sales/get_sales_trends_api/', get_sales_trends_api, name='get_sales_trends_api'),
    path('sales/get_product_sales_summary_api/<int:product_id>/', get_product_sales_summary_api, name='get_product_sales_summary_api'),
    path('sales/get_recent_sales_api/', get_recent_sales_api, name='get_recent_sales_api'),
    path('sales/get_sales_count_api/', get_sales_count_api, name='get_sales_count_api'),
    path('sales/get_total_sales_amount_api/', get_total_sales_amount_api, name='get_total_sales_amount_api'),
    path('sales/get_average_units_sold_per_sale_api/', get_average_units_sold_per_sale_api, name='get_average_units_sold_per_sale_api'),
    path('sales/get_sales_growth_rate_api/', get_sales_growth_rate_api, name='get_sales_growth_rate_api'),
    path('sales/get_average_order_value_api/', get_average_order_value_api, name='get_average_order_value_api'),
]   
