# Generated by Django 5.2.3 on 2025-10-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vehicles',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
