# Generated by Django 5.2.3 on 2025-11-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_vehicle_alter_product_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_in_store',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='home_produc_name_29ca62_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='home_produc_brand_255b66_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['part_number'], name='home_produc_part_nu_02792d_idx'),
        ),
    ]
