# Generated by Django 5.2.3 on 2025-11-09 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_quantity_in_store_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('remaining_balance', models.IntegerField(default=0)),
                ('sale', models.ForeignKey(blank=1, null=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='home.sale')),
            ],
        ),
    ]
