# Generated by Django 5.2.3 on 2025-11-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='aproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
