# Generated by Django 5.2.3 on 2025-11-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product_deleted_sale_aproved_sale_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=1, decimal_places=2, max_digits=10, null=1),
        ),
    ]
