# Generated by Django 5.2.3 on 2025-12-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_product_amount_alter_product_amount_collected_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amount',
            new_name='buying_price',
        ),
    ]
