# Generated by Django 5.2.3 on 2026-01-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
