# Generated by Django 5.2.3 on 2026-02-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_business_alter_product_company_delete_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='company',
            new_name='business',
        ),
    ]
