# Generated by Django 5.2.3 on 2026-02-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_sale_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='sale',
        ),
        migrations.AddField(
            model_name='customer',
            name='sale',
            field=models.ManyToManyField(related_name='customers', to='home.sale'),
        ),
    ]
