# Generated by Django 5.2.3 on 2026-02-15 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_customer_sale_customer_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='sale',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='home.customer'),
        ),
    ]
